---
- type: replace
  path: /releases/name=bosh-virtualbox-cpi
  value:
    name: bosh-virtualbox-cpi
    url: file:///tmp/vbox-cpi-release # bosh create-release --force --tarball /tmp/vbox-cpi-release
