name: Trigger Concourse git resource
on: [ push, workflow_dispatch ]
jobs:
  trigger-resource-check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger resource check
        uses: gstackio/trigger-concourse-resource-check-action@v1
        with:
          concourse-url:           https://ci.gstack.io
          concourse-team:          gk-plat-devs
          concourse-pipeline:      bosh-virtualbox-cpi-release
          concourse-resource:      git
          concourse-webhook-token: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
